### ISSUE TITLE
[Management]: 405 Method not allowed

### ISSUE THREAD

**Issue by michaelkrog** [docker-library/rabbitmq#173]
I am having issues with some requests using the Management UI in docker image rabbitmq:3.6-management behind an Nginx proxy.

I can log in just fine. I can even create a new user. But when I set permissions for a user og try to create an exchange, then I get HTTP 405 in reponse.

I tried copying the request to a cUrl request and this is what I get:
```
$ curl -i  'http://rabbitmq.xxxx.xx/api/exchanges/%2F/meerkat' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://rabbitmq.xxxx.xx' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36' -H 'content-type: application/json' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'authorization: Basic YWRtaW46YWRtaW4=' -H 'Cookie: m=2258:YWRtaW46YWRtaW4%253D' -H 'Connection: keep-alive' -H 'Referer: http://rabbitmq.xxxx.xx/' --data-binary '{"vhost":"/","name":"meerkat","type":"topic","durable":"true","auto_delete":"false","internal":"false","arguments":{}}' --compressed
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.13.1
Date: Mon, 26 Jun 2017 12:04:43 GMT
Content-Length: 0
Connection: keep-alive
vary: origin
allow: HEAD, GET, OPTIONS
```

Creating a user goes just fine:
```
curl -i 'http://rabbitmq.xxxx.xx/api/users/test' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://rabbitmq.xxxx.xx' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36' -H 'content-type: application/json' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'authorization: Basic YWRtaW46YWRtaW4=' -H 'Cookie: m=2258:YWRtaW46YWRtaW4%253D' -H 'Connection: keep-alive' -H 'Referer: http://rabbitmq.xxxx.xx/' --data-binary '{"username":"test","password":"test","tags":""}' --compressed
HTTP/1.1 201 Created
Server: nginx/1.13.1
Date: Mon, 26 Jun 2017 12:07:26 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
vary: accept, accept-encoding, origin
```

**Comment by michaelklishin** [comment]
@michaelkrog I somewhat doubt this has anything to do with Docker or Nginx. "Setting permissions" and "creating an exchange" are not comparable operations in the sense that they require completely different sets of permissions:

 * Permission management requires the acting user to be tagged with `administrator`. According to the 2nd `curl` line, your `admin:admin` user (base64-decoded from `YWRtaW46YWRtaW4=`) has that tag.
 * Creating an exchange only requires ["configure" permissions](http://www.rabbitmq.com/access-control.html) for the vhost in question, `/`. This is orthogonal to the ability to create new users.

[RabbitMQ management plugin docs](http://www.rabbitmq.com/management.html) explain how you can enable logging for HTTP API requests to gather more information.

**Comment by azhi** [comment]
@michaelkrog  Don't know if it's still an issue for you, but you probably hit quite known issue of nginx URL normalization - any requests that require virtual host in the uri path ('%2F') does not get proxied correctly through nginx. For details see [this](http://blog.jamesball.co.uk/2015/08/using-nginxapache-as-reverse-proxy-for.html).

**Comment by michaelkrog** [comment]
@azhi Thank you so much. It worked.

(And sorry for the late answer. I have been away for 6 months. ) :smirk:

**Comment by Rupture13** [comment]
I came to this issue via yet another path, and I fixed it in the Management UI by [specifying a new VirtualHost](https://www.tutlane.com/tutorial/rabbitmq/rabbitmq-virtual-hosts) with a normal name without "/" or anything (mine was called "vhosttest"). Having done so, I could successfully make the exchange via the UI, since now the request isn't _"corrupted"_ by a certain vhost name.

**Comment by michaelklishin** [comment]
I've added a [doc section](http://localhost:8191/management.html#http-api-proxy) about these caveats for those using the default virtual host. It's perfectly fine to override its name or delete it and use a virtual host with a name without any slashes.

**Comment by Pexers** [comment]
For any new comers, here's a working example of a cURL command to publish messages :)
- Virtual Host: `vhost`
- Exchange: `amq.direct`
- Routing Key: `my-queue`
```sh
$ curl -vvv -u ADMIN_USER:ADMIN_PWD -H "content-type:application/json" -X POST \
-d '{"properties":{"delivery_mode":2},"routing_key":"my-queue","payload":"Hello World!","payload_encoding":"string"}' \
https://my-domain/api/exchanges/vhost/amq.direct/publish
```
P.S.: be sure to use the admin user credentials.

**Comment by japita-se** [comment]
> Solved by removing in NGINX config file "/" from "proxy_pass http://localhost:15672/;" so it should be ""proxy_pass http://localhost:15672;"

Not work for me. Here is my nginx conf:
`location ~* /rabbitmq/(.*) {
                rewrite ^/rabbitmq/(.*)$ /$1 break;
                proxy_pass http://127.0.0.1:15672;
                proxy_buffering                    off;
                proxy_set_header Host              $http_host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
`

**Comment by mohammad-rj** [comment]
For anyone still struggling with this in, especially when proxying RabbitMQ through a subpath like `/rabbitmq/`, the core issue remains Nginx's handling of the URL-encoded default vhost (`%2F`).

After extensive testing, I can confirm that a two-location block configuration is the most robust solution. Simple rewrites or changes to the `proxy_pass` trailing slash were insufficient and led to either `404 Not Found` or `405 Method Not Allowed` errors.

**The definitive working solution is to use two `location` blocks in your Nginx config.** The first block specifically traps API calls that contain the encoded vhost (`%2F`), while the second block handles all other UI assets.

Here is the battle-tested configuration that solved the `405` error for me:

```nginx
# Nginx config for cockpit.example.com

# First, specifically match API calls that target the default vhost ('/'),
# which the browser URL-encodes as '%2F'. This rule must come first.
# It captures the resource type (e.g., exchanges, queues) and the rest of the URI.
location ~* ^/rabbitmq/api/([^/]+)/%2F/(.*)$ {
    # Reconstruct the correct upstream URL, forcing the encoded slash back in.
    proxy_pass http://<your_rabbitmq_host>:15672/api/$1/%2F/$2?$query_string;

    # Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

# Second, handle all other requests to the UI (JS, CSS, HTML, etc.).
# This acts as the general catch-all for the subpath.
location /rabbitmq/ {
    # Strip the /rabbitmq/ prefix before passing the request to the upstream.
    rewrite ^/rabbitmq/(.*)$ /$1 break;

    proxy_pass http://<your_rabbitmq_host>:15672;

    # Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Key Takeaway:** The trick is to isolate the problematic API calls that contain `%2F` into their own `location` block and handle them separately from the general UI traffic. While creating a new vhost without a slash is a valid architectural workaround, this Nginx configuration correctly solves the proxying problem itself.
